/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GerenciarRouteImport } from './routes/gerenciar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContagemRouteImport } from './routes/contagem'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const GerenciarRoute = GerenciarRouteImport.update({
  id: '/gerenciar',
  path: '/gerenciar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContagemRoute = ContagemRouteImport.update({
  id: '/contagem',
  path: '/contagem',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compras': typeof ComprasRoute
  '/contagem': typeof ContagemRoute
  '/dashboard': typeof DashboardRoute
  '/gerenciar': typeof GerenciarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compras': typeof ComprasRoute
  '/contagem': typeof ContagemRoute
  '/dashboard': typeof DashboardRoute
  '/gerenciar': typeof GerenciarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compras': typeof ComprasRoute
  '/contagem': typeof ContagemRoute
  '/dashboard': typeof DashboardRoute
  '/gerenciar': typeof GerenciarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compras'
    | '/contagem'
    | '/dashboard'
    | '/gerenciar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/compras' | '/contagem' | '/dashboard' | '/gerenciar'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/compras'
    | '/contagem'
    | '/dashboard'
    | '/gerenciar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ComprasRoute: typeof ComprasRoute
  ContagemRoute: typeof ContagemRoute
  DashboardRoute: typeof DashboardRoute
  GerenciarRoute: typeof GerenciarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gerenciar': {
      id: '/gerenciar'
      path: '/gerenciar'
      fullPath: '/gerenciar'
      preLoaderRoute: typeof GerenciarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contagem': {
      id: '/contagem'
      path: '/contagem'
      fullPath: '/contagem'
      preLoaderRoute: typeof ContagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ComprasRoute: ComprasRoute,
  ContagemRoute: ContagemRoute,
  DashboardRoute: DashboardRoute,
  GerenciarRoute: GerenciarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
